---
python:
- "2.7"
env:
  global:
  - secure: |-
      NFCsuN/bUok5P42i1vRedIqg/K1xpYHbml5rX5fUQIqcNyBrrpJUjgWyDLFy
      RlRvIzBOuA8KodgTIzOFl3zm4XhML7ZgWFzpnMLZp2MqYDFewdZhEXp4dyJK
      vAGr0zZOZDz1qWNHNVm1Wd+3OJjeNjcXQbzSbR8VcBMA8IM15cs=
  - secure: |-
      bzMVc8UaXRu8tEq9SV0IBEb/i8JPnFyEXPUBeNFgMUKMvX2/lla5BSOlP30C
      /YaltxZwinSwepAeXIfetuYOu12Spz6U5aqBC1WhPsA64qwiok0UMYBHyMcC
      IndtEoty+iJVZd2fQF2oq4ov0xjidF7xeFquPrhpJIuz+zp8oSk=
script: python tests.py
install: pip install -r requirements.txt --use-mirrors
language: python
